---
kind: Job
apiVersion: batch/v1
metadata:
  name: spinnaker-create-bucket
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: minio
  annotations:
    helm.sh/hook: post-install
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  selector:
    matchLabels:
      controller-uid: 95d2ca2d-2346-11e8-baf7-06dec40001b5
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: spinnaker-spinnaker
        component: minio
        controller-uid: 95d2ca2d-2346-11e8-baf7-06dec40001b5
        job-name: spinnaker-create-bucket
    spec:
      containers:
      - name: post-install-job
        image: viglesiasce/minio-client:v0.4.0
        command:
        - sh
        - "-c"
        - mc config host add spinnaker-minio http://minio.spinnaker.youxian.com spinnakeradmin
          spinnakeradmin S3v4 &&  mc mb spinnaker-minio/spinnaker
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
