---
kind: Secret
apiVersion: v1
metadata:
  name: spinnaker-jenkins
  namespace: spinnaker
  labels:
    app: spinnaker-jenkins
    chart: jenkins-0.14.0
    heritage: Tiller
    release: spinnaker
data:
  jenkins-admin-password: VEdZN0hhOUNtdg==
  jenkins-admin-user: YWRtaW4=
type: Opaque
