---
kind: Secret
apiVersion: v1
metadata:
  name: spinnaker-minio-user
  namespace: spinnaker
  labels:
    app: spinnaker-minio
    chart: minio-0.5.5
    heritage: Tiller
    release: spinnaker
data:
  accesskey: c3Bpbm5ha2VyYWRtaW4=
  secretkey: c3Bpbm5ha2VyYWRtaW4=
type: Opaque
