apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-lb
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      serviceAccountName: nginx-ingress
      terminationGracePeriodSeconds: 60
      containers:
      - image: registry.youxian.com/kubernetes/nginxingress:0.11.0
        name: nginx-ingress-lb
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_MASTER
            value: http://kube-api.youxian.com:8080
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - /nginx-ingress-controller
        - "--default-backend-service=$(POD_NAMESPACE)/default-http-backend"
        - "--configmap=$(POD_NAMESPACE)/nginx-configuration"
        - "--apiserver-host=http://kube-api.youxian.com:8080"
        - "--sort-backends"
        - "--tcp-services-configmap=$(POD_NAMESPACE)/tcp-ops-lbs-py"
        - "--udp-services-configmap=$(POD_NAMESPACE)/udp-ops-lbs-py"
        - "--annotations-prefix=nginx.ingress.kubernetes.io"
