---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spinnaker-spinnaker-front50
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: front50
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker-spinnaker
      component: front50
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: spinnaker-spinnaker
        component: front50
    spec:
      volumes:
      - name: spinnaker-spinnaker-spinnaker-config
        configMap:
          name: spinnaker-spinnaker-spinnaker-config
          defaultMode: 420
      - name: spinnaker-front50-config
        configMap:
          name: spinnaker-front50-config
          defaultMode: 420
      containers:
      - name: front50
        image: gcr.io/spinnaker-marketplace/front50:0.9.0-20180221133510
        ports:
        - name: front50
          containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: spinnaker-spinnaker-spinnaker-config
          mountPath: "/opt/spinnaker/config"
        - name: spinnaker-front50-config
          mountPath: "/opt/front50/config"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
