---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spinnaker-spinnaker-clouddriver
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: clouddriver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker-spinnaker
      component: clouddriver
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: spinnaker-spinnaker
        component: clouddriver
    spec:
      volumes:
      - name: spinnaker-spinnaker-spinnaker-config
        configMap:
          name: spinnaker-spinnaker-spinnaker-config
          defaultMode: 420
      - name: spinnaker-kubeapi-config
        configMap:
          name: spinnaker-kubeapi-config
          defaultMode: 420
      - name: spinnaker-spinnaker-registry
        secret:
          secretName: spinnaker-spinnaker-registry
          defaultMode: 420
      - name: spinnaker-clouddriver-config
        configMap:
          name: spinnaker-clouddriver-config
          defaultMode: 0644
      containers:
      - name: clouddriver
        image: gcr.io/spinnaker-marketplace/clouddriver:2.0.0-20180221152902
        ports:
        - name: clouddriver
          containerPort: 7002
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: spinnaker-spinnaker-spinnaker-config
          mountPath: "/opt/spinnaker/config"
        - name: spinnaker-kubeapi-config
          mountPath: "/opt/spinnaker/config"
        - name: spinnaker-spinnaker-registry
          mountPath: "/tmp/registry"
        - name: spinnaker-clouddriver-config
          mountPath: "/opt/clouddriver/config"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 7002
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
