---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spinnaker-spinnaker-deck
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: deck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker-spinnaker
      component: deck
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: spinnaker-spinnaker
        component: deck
    spec:
      volumes:
      - name: spinnaker-spinnaker-spinnaker-config
        configMap:
          name: spinnaker-spinnaker-spinnaker-config
          defaultMode: 420
      containers:
      - name: deck
        image: gcr.io/spinnaker-marketplace/deck:2.1.0-20180221143146
        ports:
        - name: deck
          containerPort: 9000
          protocol: TCP
        env:
        - name: API_HOST
          value: http://gate.spinnaker.youxian.com
        - name: DECK_HOST
          value: 0.0.0.0
        - name: DECK_PORT
          value: '9000'
        resources: {}
        volumeMounts:
        - name: spinnaker-spinnaker-spinnaker-config
          mountPath: "/opt/spinnaker/config"
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
