---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spinnaker-spinnaker-gate
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: gate
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker-spinnaker
      component: gate
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: spinnaker-spinnaker
        component: gate
      annotations:
        checksum/config: 9f6777e4578dcb8f3083ce1e514eb789d126b2e26837ea97cd6cf8f7d6e03462
    spec:
      volumes:
      - name: spinnaker-spinnaker-spinnaker-config
        configMap:
          name: spinnaker-spinnaker-spinnaker-config
          defaultMode: 420
      volumes:
      - name: spinnaker-gate-config
        configMap:
          name: spinnaker-gate-config
          defaultMode: 0644
      containers:
      - name: gate
        image: gcr.io/spinnaker-marketplace/gate:0.10.0-20180221133510
        ports:
        - name: gate
          containerPort: 8084
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: spinnaker-spinnaker-spinnaker-config
          mountPath: "/opt/spinnaker/config"
        - name: spinnaker-gate-config
          mountPath: "/opt/gate/config"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8084
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
