apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  labels:
    name: ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ui-apps
    spec:
      containers:
      - name: ui-app
        image: vmware/harbor-ui:v1.4.0
        imagePullPolicy: IfNotPresent
        env:
          - name: CONFIG_PATH
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: CONFIG_PATH
          - name: LOG_LEVEL
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: LOG_LEVEL
          - name: UI_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: JOBSERVICE_SECRET
          - name: GODEBUG
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: GODEBUG
          - name: JobServiceURL
            valueFrom:
              configMapKeyRef:
               name: harbor-ui-config
               key: JobServiceURL
          - name: ADMINSERVER_URL
            valueFrom:
              configMapKeyRef:
               name: harbor-ui-config
               key: ADMINSERVER_URL
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/ui
      volumes:
      - name: config
        configMap:
          name: harbor-ui-config
          items:
          - key: config
            path: app.conf
          - key: pkey
            path: private_key.pem
          - key: SECRET_KEY
            path: key
