kind: ConfigMap
apiVersion: v1
metadata:
  name: spinnaker-front50-config
  namespace: spinnaker
  labels:
    app: spinnaker-front50
    chart: front50-0.10.0
    heritage: Tiller
    release: spinnaker
data:
  front50.yml: |-
    server:
      port: 8080

    management:
      health:
        redis:
          enabled: ${spinnaker.redis.enabled}
          host: redis.spinnaker.youxian.com
          port: 6379
    cassandra:
      enabled: false

    spinnaker:
      cassandra:
        enabled: false
        embedded: true
        cluster: CASS_SPINNAKER
        keyspace: front50
        name: default
      redis:
        enabled: true
        host: redis.spinnaker.youxian.com
        port: 6379

    swagger:
      enabled: true
      title: Spinnaker Front50 API
      description:
      contact:
      patterns:
        - /default/.*
        - /credentials.*
        - /global/.*
        - /notifications.*
        - /pipelines.*
        - /strategies.*
        - /v2/.*
