---
kind: ConfigMap
apiVersion: v1
metadata:
  name: spinnaker-spinnaker-tests
  namespace: spinnaker
data:
  run.sh: |-
    @test "Testing Spinnaker UI is accessible" {
      curl --retry 12 --retry-delay 10 spinnaker-spinnaker-deck:9000
    }
