---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spinnaker-jenkins
  namespace: spinnaker
  labels:
    app: spinnaker-jenkins
    chart: jenkins-0.14.0
    heritage: Tiller
    release: spinnaker
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: jenkins-pv
