---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spinnaker-redis
  namespace: spinnaker
  labels:
    app: spinnaker-redis
    chart: redis-1.1.17
    heritage: Tiller
    release: spinnaker
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeName: redis-pv
