---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spinnaker-minio
  namespace: spinnaker
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: minio-pv
