---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
spec:
  capacity:
    storage: 8Gi
  hostPath:
    path: "/home/jenkins"
    type: ''
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: spinnaker
    name: spinnaker-jenkins
    uid: 95b6f08b-2346-11e8-baf7-06dec40001b5
    apiVersion: v1
    resourceVersion: '143630'
  persistentVolumeReclaimPolicy: Retain
