---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: "/home/minio"
    type: ''
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: spinnaker
    name: spinnaker-minio
    uid: 95b74a04-2346-11e8-baf7-06dec40001b5
    apiVersion: v1
    resourceVersion: '143631'
  persistentVolumeReclaimPolicy: Retain
