---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 8Gi
  hostPath:
    path: "/home/redis"
    type: ''
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
