kind: Service
apiVersion: v1
metadata:
  name: spinnaker-jenkins
  namespace: spinnaker
  labels:
    app: spinnaker-jenkins
    chart: jenkins-0.14.0
    component: spinnaker-jenkins-master
    heritage: Tiller
    release: spinnaker
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    component: spinnaker-jenkins-master
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
