kind: Service
apiVersion: v1
metadata:
  name: spinnaker-jenkins-agent
  namespace: spinnaker
  labels:
    app: spinnaker-jenkins
    chart: jenkins-0.14.0
    component: spinnaker-jenkins-master
spec:
  ports:
  - name: slavelistener
    protocol: TCP
    port: 50000
    targetPort: 50000
  selector:
    component: spinnaker-jenkins-master
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
