kind: Service
apiVersion: v1
metadata:
  name: spinnaker-redis
  namespace: spinnaker
  labels:
    app: spinnaker-redis
    chart: redis-1.1.17
    heritage: Tiller
    release: spinnaker
spec:
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: redis
  selector:
    app: spinnaker-redis
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
