---
kind: Service
apiVersion: v1
metadata:
  name: spinnaker-spinnaker-orca
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: orca
spec:
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  selector:
    app: spinnaker-spinnaker
    component: orca
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
