---
kind: Service
apiVersion: v1
metadata:
  name: spinnaker-spinnaker-gate
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: gate
spec:
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084
  selector:
    app: spinnaker-spinnaker
    component: gate
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
