---
kind: Service
apiVersion: v1
metadata:
  name: spinnaker-spinnaker-igor
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: igor
spec:
  ports:
  - name: igor
    protocol: TCP
    port: 8088
    targetPort: 8088
  - name: jenkins-master
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: jenkins-agent
    protocol: TCP
    port: 50000
    targetPort: 50000
  selector:
    app: spinnaker-spinnaker
    component: igor
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
