---
kind: Service
apiVersion: v1
metadata:
  name: spinnaker-spinnaker-front50
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: front50
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: spinnaker-spinnaker
    component: front50
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
