---
kind: Service
apiVersion: v1
metadata:
  name: spinnaker-minio-svc
  namespace: spinnaker
  labels:
    app: spinnaker-minio
    chart: minio-0.5.5
    heritage: Tiller
    release: spinnaker
spec:
  ports:
  - name: service
    protocol: TCP
    port: 9000
    targetPort: 9000
  selector:
    app: spinnaker-minio
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
