---
kind: Service
apiVersion: v1
metadata:
  name: spinnaker-spinnaker-clouddriver
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: clouddriver
spec:
  ports:
  - protocol: TCP
    port: 7002
    targetPort: 7002
  selector:
    app: spinnaker-spinnaker
    component: clouddriver
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
