---
kind: Service
apiVersion: v1
metadata:
  name: spinnaker-spinnaker-echo
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: echo
spec:
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
  selector:
    app: spinnaker-spinnaker
    component: echo
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
