kind: Service
apiVersion: v1
metadata:
  name: spinnaker-spinnaker-rosco
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: rosco
spec:
  ports:
  - protocol: TCP
    port: 8087
    targetPort: 8087
  selector:
    app: spinnaker-spinnaker
    component: rosco
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
