apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: spinnaker
spec:
  rules:
  - host: jenkins.spinnaker.youxian.com
    http:
      paths:
      - path: /
        backend:
          serviceName: spinnaker-jenkins
          servicePort: 8080
