apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: gate-ingress
  namespace: spinnaker
spec:
  rules:
  - host: spinnaker.youxian.com
    http:
      paths:
      - path: /gate
        backend:
          serviceName: spinnaker-spinnaker-gate
          servicePort: 8084
