apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: igor-ingress
  namespace: spinnaker
spec:
  rules:
  - host: igor.spinnaker.youxian.com
    http:
      paths:
      - path: /
        backend:
          serviceName: spinnaker-spinnaker-igor
          servicePort: 8088
