apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gate-ingress
  namespace: spinnaker
spec:
  rules:
  - host: gate.spinnaker.youxian.com
    http:
      paths:
      - path: /
        backend:
          serviceName: spinnaker-spinnaker-gate
          servicePort: 8084
