apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rosco-ingress
  namespace: spinnaker
spec:
  rules:
  - host: rosco.spnnaker.youxian.com
    http:
      paths:
      - path: /
        backend:
          serviceName: spinnaker-spinnaker-rosco
          servicePort: 8087
